apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: gitlab80
        - containerPort: 22
          name: gitlab22
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - name: gitlab-pvc-config
          mountPath: /etc/gitlab
        - name: gitlab-pvc-logs
          mountPath: /var/log/gitlab
        - name: gitlab-pvc-data
          mountPath: /var/opt/gitlab
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://gitlab.hsiangya.top'
      volumes:
      - name: gitlab-pvc-config
        persistentVolumeClaim:
          claimName: gitlab-pvc-config
      - name: gitlab-pvc-logs
        persistentVolumeClaim:
          claimName: gitlab-pvc-logs
      - name: gitlab-pvc-data
        persistentVolumeClaim:
          claimName: gitlab-pvc-data
