apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dev
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    # nodePort: 30306  # 你可以指定一个特定的端口，或者让Kubernetes自动分配
  selector:
    app: mysql
