apiVersion: v1
kind: Namespace
metadata:
  name: dev
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: mongodb-config
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    security:
      authorization: "enabled"
