apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-nfs-storage
